FullName = input("Please input your FullName : ")
Age = input("Please input your Age : ")
HomeTown = input("Please input your home town : ")
Religion = input("Please input your religion : ")
Birthplace = input("Please input your birthplace : ")
Birthdate = input("Please input your birthdate : ")
Favoritefood = input("Please input your favoritefood : ")
Hobbies = input("Please input your hobbies : ")
Favoritecolor = input("Please input your favoritecolor : ")
Sports = input("Please input your sports : ")
School = input("Please input your school : ")
Goal = input("Please input your Goal : ")



print("Hi my name is" + FullName + "and i'm" , Age , "yrs old \n i live in" , HomeTown , "i'am" , Religion , "\n" "i was born in" , Birthplace , "In the year" , Birthdate , "\n" "My favoritefood is" , Favoritefood , "The thing i like to do is" , Hobbies , "\n" "i like the color" , Favoritecolor , "i love to play" , Sports , "\n" "I study at the" , School , "My goal in life is" , Goal ,)
